### ISSUE TITLE
[Technical] Implement LTI Connection for Moodle

### ISSUE THREAD

**Issue by MarcNor** [HASKI-RAK/HASKI-Backend#19]
**Describe the feature to be developed **
We need a LTI connection for authentication in HASKI. We will use [pylti](https://github.com/dmitry-viskov/pylti1.3) for this.

**Describe the Impact on the System**
It needs to be implemented as an API endpoint and therefore will not impact the overall system structure too much. We have to check on any other endpoint that we have the right rights set via cookies.

**Definition of Done**
What needs to be done, before the Issue can be closed?
- [x] Linting Code to Python standard
- [ ] Testing code with Pytest. All tests within the system should still be ok.
- [x] Check naming for meaningful names
- [x] Check LTI for setting cookies correct
- [x] LTI should not accept other platforms than our moodle specified
- [x] LTI should be able to reject users, who are not allowed to enter HASKI

**Comment by theUpsider** [comment]
Formatting issues currently.
